/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hadoop_compression_lzo_FpgaDecompressor */

#ifndef _Included_com_hadoop_compression_lzo_FpgaDecompressor
#define _Included_com_hadoop_compression_lzo_FpgaDecompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hadoop_compression_lzo_FpgaDecompressor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hadoop_compression_lzo_FpgaDecompressor__1_1initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_hadoop_compression_lzo_FpgaDecompressor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hadoop_compression_lzo_FpgaDecompressor__1_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_hadoop_compression_lzo_FpgaDecompressor
 * Method:    __decompressBytesDirect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hadoop_compression_lzo_FpgaDecompressor__1_1decompressBytesDirect
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
